//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaCT.Feeds {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Feeds.FeedsSoap")]
    public interface FeedsSoap {
        
        // CODEGEN: Generating message contract since element name GetAggregatedFeedsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAggregatedFeeds", ReplyAction="*")]
        LojaCT.Feeds.GetAggregatedFeedsResponse GetAggregatedFeeds(LojaCT.Feeds.GetAggregatedFeedsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAggregatedFeeds", ReplyAction="*")]
        System.Threading.Tasks.Task<LojaCT.Feeds.GetAggregatedFeedsResponse> GetAggregatedFeedsAsync(LojaCT.Feeds.GetAggregatedFeedsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAggregatedFeedsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAggregatedFeeds", Namespace="http://tempuri.org/", Order=0)]
        public LojaCT.Feeds.GetAggregatedFeedsRequestBody Body;
        
        public GetAggregatedFeedsRequest() {
        }
        
        public GetAggregatedFeedsRequest(LojaCT.Feeds.GetAggregatedFeedsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAggregatedFeedsRequestBody {
        
        public GetAggregatedFeedsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAggregatedFeedsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAggregatedFeedsResponse", Namespace="http://tempuri.org/", Order=0)]
        public LojaCT.Feeds.GetAggregatedFeedsResponseBody Body;
        
        public GetAggregatedFeedsResponse() {
        }
        
        public GetAggregatedFeedsResponse(LojaCT.Feeds.GetAggregatedFeedsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAggregatedFeedsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAggregatedFeedsResult;
        
        public GetAggregatedFeedsResponseBody() {
        }
        
        public GetAggregatedFeedsResponseBody(System.Xml.Linq.XElement GetAggregatedFeedsResult) {
            this.GetAggregatedFeedsResult = GetAggregatedFeedsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedsSoapChannel : LojaCT.Feeds.FeedsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedsSoapClient : System.ServiceModel.ClientBase<LojaCT.Feeds.FeedsSoap>, LojaCT.Feeds.FeedsSoap {
        
        public FeedsSoapClient() {
        }
        
        public FeedsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LojaCT.Feeds.GetAggregatedFeedsResponse LojaCT.Feeds.FeedsSoap.GetAggregatedFeeds(LojaCT.Feeds.GetAggregatedFeedsRequest request) {
            return base.Channel.GetAggregatedFeeds(request);
        }
        
        public System.Xml.Linq.XElement GetAggregatedFeeds() {
            LojaCT.Feeds.GetAggregatedFeedsRequest inValue = new LojaCT.Feeds.GetAggregatedFeedsRequest();
            inValue.Body = new LojaCT.Feeds.GetAggregatedFeedsRequestBody();
            LojaCT.Feeds.GetAggregatedFeedsResponse retVal = ((LojaCT.Feeds.FeedsSoap)(this)).GetAggregatedFeeds(inValue);
            return retVal.Body.GetAggregatedFeedsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LojaCT.Feeds.GetAggregatedFeedsResponse> LojaCT.Feeds.FeedsSoap.GetAggregatedFeedsAsync(LojaCT.Feeds.GetAggregatedFeedsRequest request) {
            return base.Channel.GetAggregatedFeedsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LojaCT.Feeds.GetAggregatedFeedsResponse> GetAggregatedFeedsAsync() {
            LojaCT.Feeds.GetAggregatedFeedsRequest inValue = new LojaCT.Feeds.GetAggregatedFeedsRequest();
            inValue.Body = new LojaCT.Feeds.GetAggregatedFeedsRequestBody();
            return ((LojaCT.Feeds.FeedsSoap)(this)).GetAggregatedFeedsAsync(inValue);
        }
    }
}
